### PR TITLE
Fix for lists and ByteArrays

### LINKED ISSUE #116: [BUG] Unwrap errors & Cannot read property
Hello,

I've discovered other 'bugs' on with parsing some deploys on testnet : 

```
Tried to unwrap Error: 0
Cannot read property 'toBytes' of undefined
Tried to unwrap Error: Left over bytes
Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch
TypeError: _a.toHex is not a function
```

Here's the full log : 

[testnetsdk.txt](https://github.com/casper-ecosystem/casper-js-sdk/files/7297216/testnetsdk.txt)

48 deploys or so can't be parsed on testnet actually (over 20k~ excluding transfers) : 
```
Failed to fetch deploy : cbae817bb86a817017853ed9698a3b53b8f1151de823c4028e1072f66a969c68
Failed to fetch deploy : e3214991abe2cfe4f7093b84c60686ae9806dcc13551b55e38660e969bfaacff
Failed to fetch deploy : f4be922dd9effd15e3706b4058395e451553863d1460b0a455f96b767608416a
Failed to fetch deploy : e685b1996e93a2d099f14bc94fb696f29a3ea7be232c5db3d035098c677ad0f6
Failed to fetch deploy : 4cc2c31e422ce617765ba003dceeefbef64669bea5f42110476315a532f0f8fd
Failed to fetch deploy : 244d731044e1b7059507b9191a041844e93c8afa8789f03b5c5632ea85a7e286
Failed to fetch deploy : 443fc44bafb3ab767f3398bd2abb7599e15b4e6bae92a2a1c69363f5fc5c1edc
Failed to fetch deploy : 5c43215bae1f78bd04dd1b1e9b6a56f02b1807031dac3f2f9771465adedf8e7e
Failed to fetch deploy : d057d876113c37160bd297e4792a002c8e0d477dc62c8b36f3cfc637f4ad596c
Failed to fetch deploy : 90772ae212402838d0ab9ff3c323157619fc57eb32003160f52608647f234d4a
Failed to fetch deploy : 0ec1bb3d3ec452869ea0feb0c05a521c9870994122ddd4ade8cd86e75e064835
Failed to fetch deploy : 60ca8b422032fcadabed38a108088316212f1fb9d32bc6ae55ccdbb5781cfb00
Failed to fetch deploy : 82c8257f4caddf34e8efe7b60fc3ce6731a9e488669d63b6df0034b5593d4d34
Failed to fetch deploy : aac1b785bae88ed4367ef9b4021293ffee00e09506f56cecf6b67f8c2ce01551
Failed to fetch deploy : 9db79460e31a665174193cde565fd8bf101a70e94b268dc62cd4295d983ee87d
Failed to fetch deploy : 4d455de4a36ce0fde47b6a84e59652e4ddd103f59e91fb694d04b308912af979
Failed to fetch deploy : 34f48231b501c112edfc16f6a04fe26bda2fcea129d078f8f41cabedebbb5d39
Failed to fetch deploy : 125e913c232013787e396523ff6dc7e90cbbde1c7217752063719f48abc45003
Failed to fetch deploy : 2d025da629812d3c2e84d11c21ba7e6dd9ac13e94b4ba4c79a7b3c86c1b381a3
Failed to fetch deploy : 3b31d8ef5d7333cfcbf4cb54faef5d5b971a5d3a652ae0a13457289e53920ef8
Failed to fetch deploy : ee6c7b76f2d75ae364413509327c2b38aa9eb0dc85cdaab3b99902238f336a37
Failed to fetch deploy : 308c11f2d81712be993b7913b633798260d84d017328f43b29da8052f01a2591
Failed to fetch deploy : 13e18a7f6798e43291c0abf0dd8e8b027fd0d8428a62ec5455682aab7a558d20
Failed to fetch deploy : 0e2f61aa54d9e9e6fc9b86269ebc3baf5a6534bab26cc028dea7133664884579
Failed to fetch deploy : 7ce7d518a56221a025e8bde3d165183bac001af8f6fae1464c17bf0a2f04f22b
Failed to fetch deploy : 2d8c8a81fc2a65eadbe47f3a79105321db496cfcc05a2babf7e35550f9d809e0
Failed to fetch deploy : 3aeb2ad2b209291fa3d15166cdd6768cfeae91414533a39961b3c69dd83bf8f7
Failed to fetch deploy : bd2f9540c284d315e940b9febdc7355890a599e60f2f64b125452398a9f5cf5a
Failed to fetch deploy : 2c36fe6ca5c7c8da052d22b5c08f5eeecd8afc00ce4aaea0f330a554b953804d
Failed to fetch deploy : 228c4fe9051598942f9113f330b060fd21152ae5a4ce2975ebcd6776d6967b1b
Failed to fetch deploy : aaa73fd21be9b7f19fc3cf5ced3798ce4d88a430f90ba006827e1979fac870ff
Failed to fetch deploy : 99ec1652af0220656f093f5d6796ec578011284a53ce1927fd20abf37e8dd4c8
Failed to fetch deploy : e7f4a859f984237fed9a97382d4ec3e52c73b6f17ab96b18257994e425297ba2
Failed to fetch deploy : 193a10ab287004e1d02c35c8c3d1375935e0cdee571b8bc0e72146e1884a8428
Failed to fetch deploy : e81ca82022a14989ad5c238f1e07decb663d494b0e0637813b3c7d60697ebca4
Failed to fetch deploy : 5d85732f56ecc643c2e1d27eacccf4d168da9d5aaa55dd71adcfd977ade3c4ba
Failed to fetch deploy : 18d2371f2141534a7e8b4cafac01aa9e6b921974264dc5490206d46602f4a176
Failed to fetch deploy : efe6bef366b4bc9ead3b7e04be6f8eac8ed42da8a55dc4eda922f7927bd3dfb3
Failed to fetch deploy : 049f058cf0bba42788ccac4f25633204beecde1590a0ee92371fffd2d930ec6f
Failed to fetch deploy : 0deebaa3044edda5c976de0e3f407397b136fa994831768ed6979d63f154adca
Failed to fetch deploy : 24cc3298694f3c345fc95d587207742d669928934ba989fa15660e41f31cd390
Failed to fetch deploy : b691e73b537a9431c3416c99bd615d25a285e5e3b4cc226a82426f89ae23c112
Failed to fetch deploy : 6d302c9d7c2db5f59d97ce70a86de56b18aac67d0c2f1002277e9d294db73194
Failed to fetch deploy : 1e32504f887df2e33db07cd9b48567290614c943f3518c06b7787d469b0b726b
Failed to fetch deploy : ce6bfc9a7d7b20c6ee774fbba73d77f996ffbdb0a5d814aa7e8248f9eda92f3d
Failed to fetch deploy : cbed94db7c5a7e4a544a11d85f4c46e393f7b4fc31af586ea0251b5769a8216e
Failed to fetch deploy : 0b58224988d377e412e7d7e108c547efd8ea3984f85e0b1e516f26c9ead09fd6
Failed to fetch deploy : 23cfd1c93c83c4056a3f14846270de7fe7131a6b2639873472d33403038651fb
```

Some of them contains lists and maybe this type isn't supported yet ?

### LINKED ISSUE #118: Add length checks for ByteArray type in CLValue

### PR DESCRIPTION
**Pull request by hoffmannjan**
* Fixes problems with `Lists` containing multiple `Keys` containing `Hash` or `ByteArray`
* Fixes problem with `ByteArray` with size different than 32 bytes.

### CODE REVIEW

**Comment by KillianH** [comment]
Hey,

here's my result with the testnet : 
Deploys KO :
```
aaa73fd21be9b7f19fc3cf5ced3798ce4d88a430f90ba006827e1979fac870ff
0ec1bb3d3ec452869ea0feb0c05a521c9870994122ddd4ade8cd86e75e064835
ce6bfc9a7d7b20c6ee774fbba73d77f996ffbdb0a5d814aa7e8248f9eda92f3d
cbae817bb86a817017853ed9698a3b53b8f1151de823c4028e1072f66a969c68
5d85732f56ecc643c2e1d27eacccf4d168da9d5aaa55dd71adcfd977ade3c4ba
0deebaa3044edda5c976de0e3f407397b136fa994831768ed6979d63f154adca
18d2371f2141534a7e8b4cafac01aa9e6b921974264dc5490206d46602f4a176
193a10ab287004e1d02c35c8c3d1375935e0cdee571b8bc0e72146e1884a8428
e81ca82022a14989ad5c238f1e07decb663d494b0e0637813b3c7d60697ebca4
60ca8b422032fcadabed38a108088316212f1fb9d32bc6ae55ccdbb5781cfb00
6d302c9d7c2db5f59d97ce70a86de56b18aac67d0c2f1002277e9d294db73194
1e32504f887df2e33db07cd9b48567290614c943f3518c06b7787d469b0b726b
125e913c232013787e396523ff6dc7e90cbbde1c7217752063719f48abc45003
7ce7d518a56221a025e8bde3d165183bac001af8f6fae1464c17bf0a2f04f22b
5c43215bae1f78bd04dd1b1e9b6a56f02b1807031dac3f2f9771465adedf8e7e
9db79460e31a665174193cde565fd8bf101a70e94b268dc62cd4295d983ee87d
82c8257f4caddf34e8efe7b60fc3ce6731a9e488669d63b6df0034b5593d4d34
e7f4a859f984237fed9a97382d4ec3e52c73b6f17ab96b18257994e425297ba2
aac1b785bae88ed4367ef9b4021293ffee00e09506f56cecf6b67f8c2ce01551
3b31d8ef5d7333cfcbf4cb54faef5d5b971a5d3a652ae0a13457289e53920ef8
90772ae212402838d0ab9ff3c323157619fc57eb32003160f52608647f234d4a
e3214991abe2cfe4f7093b84c60686ae9806dcc13551b55e38660e969bfaacff
228c4fe9051598942f9113f330b060fd21152ae5a4ce2975ebcd6776d6967b1b
fe83d12e0d3b945745a1d94544bcd71f551af67bbc4c1d733ca750ea8c8306f9
f4be922dd9effd15e3706b4058395e451553863d1460b0a455f96b767608416a
24cc3298694f3c345fc95d587207742d669928934ba989fa15660e41f31cd390
99ec1652af0220656f093f5d6796ec578011284a53ce1927fd20abf37e8dd4c8
0e2f61aa54d9e9e6fc9b86269ebc3baf5a6534bab26cc028dea7133664884579
4cc2c31e422ce617765ba003dceeefbef64669bea5f42110476315a532f0f8fd
ce46b1234ac79c7b0b4901b2df0dd612b34a7205c0980a8cb4b941d3ceb2c4b2
9bcf8c15f111be6adb7c5c7601e47de6ec0ecfa226e471ee8d5728cc9e1fb1dd
13e18a7f6798e43291c0abf0dd8e8b027fd0d8428a62ec5455682aab7a558d20
23cfd1c93c83c4056a3f14846270de7fe7131a6b2639873472d33403038651fb
b691e73b537a9431c3416c99bd615d25a285e5e3b4cc226a82426f89ae23c112
049f058cf0bba42788ccac4f25633204beecde1590a0ee92371fffd2d930ec6f
bfd2542e3ba4bf6bcf28ef5965233c34be0cc32c25191de782ef76f5a33460d0
754f0ecf726d66032dfb3ee1ad181585fb109f976dbc22fa7759173193119516
6d7dbd3f2c72a1fc3a2effa18be9e2b7cf6a4574bdb91bbe171c56dd1285321a
e8e5b1c7f395a03820fa26200a26f3f10f2fa6a009508bd5688c374b4fb5fb7c
443fc44bafb3ab767f3398bd2abb7599e15b4e6bae92a2a1c69363f5fc5c1edc
e6a035f2c8335441a5a603b46c3a73bdd118bdb6e70ba7a6f2b5af7c12305be2
3aeb2ad2b209291fa3d15166cdd6768cfeae91414533a39961b3c69dd83bf8f7
4d455de4a36ce0fde47b6a84e59652e4ddd103f59e91fb694d04b308912af979
4017c4c3ba47d5d26934247ecdf4c41d06005f4c7d5e1723317fd5877449e8b2
d45d3ca68bee50dcf5b139a723d407b4b6a237c3081b1bffed15835206eb61e4
1eea0ed5ab843af2c5cb189bb13b3094d07d9389e2e04417e26c8c2a53004a6b
c7509dec5f8fbfa6a2753c2f5980691ba8eba5dc187f38dea04629d61d2473a7
5899add0de77771afebfde21ee47ea1963bc3b854af444bcc1d6c95840f513e4
e2bed34a3b8ea4af52c39f0baef6492ae05cd59da3883328e34eb8b943b15425
308c11f2d81712be993b7913b633798260d84d017328f43b29da8052f01a2591
e67f0d6a221a2228b1dff42af4aeb6082cc1506b4f751317add086be5c841c36
fb60fd74f35738d161a189452258388b994bfa25a436f04d23d1621e47d9962f
1db9100a28d6f21f55d175d3e9e6d2d8a16ec3394e6660c8ac6c5106aa4bbab6
cab7a742e660cb84fb36a0a7ee432c397dd9f56f1f27f38d5994fb14bb973ee1
2d8c8a81fc2a65eadbe47f3a79105321db496cfcc05a2babf7e35550f9d809e0
cbed94db7c5a7e4a544a11d85f4c46e393f7b4fc31af586ea0251b5769a8216e
0b58224988d377e412e7d7e108c547efd8ea3984f85e0b1e516f26c9ead09fd6
0fc55ccbdb0c9a145e0517c08c4068b43a942e0147f6393d89a4690cb788087c
ee6c7b76f2d75ae364413509327c2b38aa9eb0dc85cdaab3b99902238f336a37
d057d876113c37160bd297e4792a002c8e0d477dc62c8b36f3cfc637f4ad596c
244d731044e1b7059507b9191a041844e93c8afa8789f03b5c5632ea85a7e286
1b53b81a7df5aea7d899663787ca4ae23482997612ba5312cb2521602b5b7f66
2d025da629812d3c2e84d11c21ba7e6dd9ac13e94b4ba4c79a7b3c86c1b381a3
34f48231b501c112edfc16f6a04fe26bda2fcea129d078f8f41cabedebbb5d39
e5aac80274490685a015e954b8e761b3996358967b3896641b675e9f6db68703
d69b919b2a1056b3fa59c88863a11c989496c40e2ee1e9f4d5fe4b7f08d7fcc4
e685b1996e93a2d099f14bc94fb696f29a3ea7be232c5db3d035098c677ad0f6
3f4df2f68a94a7340a9a010b26a9a3425b685dad9cd17ab359cbe66687d2becc
efe6bef366b4bc9ead3b7e04be6f8eac8ed42da8a55dc4eda922f7927bd3dfb3
2c36fe6ca5c7c8da052d22b5c08f5eeecd8afc00ce4aaea0f330a554b953804d
bd2f9540c284d315e940b9febdc7355890a599e60f2f64b125452398a9f5cf5a
1c09636fc22a4c54598b370db181c16f26c0e4a735b587710820bcd6cc09a456
5380b160ad62b3cabc83a62eaec9ac1cfdddfb16753da963967486d059c42c45
```
Transfers KO :
```
482a4704c4835205e70bcf70379cb5250a063e35b0d73f7cfb54263fb58cb478
0cace0cdd32e32f2ae9590ddcfcd3017d42bf08a426f29f60cddf730e74b2f8e
aa83cd17bd3a2147b40737b58d35fc102f39125c1d6c756e8e58eed1e7229efd
```

You can test those with the same code in the issue #116  

Errors types encountered :
```
Error: Tried to unwrap Error: Left over bytes
Deploy : aaa73fd21be9b7f19fc3cf5ced3798ce4d88a430f90ba006827e1979fac870ff KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 0ec1bb3d3ec452869ea0feb0c05a521c9870994122ddd4ade8cd86e75e064835 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : ce6bfc9a7d7b20c6ee774fbba73d77f996ffbdb0a5d814aa7e8248f9eda92f3d KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : cbae817bb86a817017853ed9698a3b53b8f1151de823c4028e1072f66a969c68 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 5d85732f56ecc643c2e1d27eacccf4d168da9d5aaa55dd71adcfd977ade3c4ba KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 0deebaa3044edda5c976de0e3f407397b136fa994831768ed6979d63f154adca KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 18d2371f2141534a7e8b4cafac01aa9e6b921974264dc5490206d46602f4a176 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 193a10ab287004e1d02c35c8c3d1375935e0cdee571b8bc0e72146e1884a8428 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : e81ca82022a14989ad5c238f1e07decb663d494b0e0637813b3c7d60697ebca4 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 60ca8b422032fcadabed38a108088316212f1fb9d32bc6ae55ccdbb5781cfb00 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 6d302c9d7c2db5f59d97ce70a86de56b18aac67d0c2f1002277e9d294db73194 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 1e32504f887df2e33db07cd9b48567290614c943f3518c06b7787d469b0b726b KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 125e913c232013787e396523ff6dc7e90cbbde1c7217752063719f48abc45003 KO

TypeError: Cannot read property 'toBytes' of undefined
Deploy : 7ce7d518a56221a025e8bde3d165183bac001af8f6fae1464c17bf0a2f04f22b KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 178,25,82,107,179,57,240,79,150,234,90,36,8,84,174,243,139,70,25,207,174,110,27,191,101,244,83,93,126,36,130,7, 
Error: Tried to unwrap Error: Left over bytes
Deploy : 5c43215bae1f78bd04dd1b1e9b6a56f02b1807031dac3f2f9771465adedf8e7e KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 9db79460e31a665174193cde565fd8bf101a70e94b268dc62cd4295d983ee87d KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 82c8257f4caddf34e8efe7b60fc3ce6731a9e488669d63b6df0034b5593d4d34 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : e7f4a859f984237fed9a97382d4ec3e52c73b6f17ab96b18257994e425297ba2 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : aac1b785bae88ed4367ef9b4021293ffee00e09506f56cecf6b67f8c2ce01551 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 3b31d8ef5d7333cfcbf4cb54faef5d5b971a5d3a652ae0a13457289e53920ef8 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 90772ae212402838d0ab9ff3c323157619fc57eb32003160f52608647f234d4a KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : e3214991abe2cfe4f7093b84c60686ae9806dcc13551b55e38660e969bfaacff KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 228c4fe9051598942f9113f330b060fd21152ae5a4ce2975ebcd6776d6967b1b KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : fe83d12e0d3b945745a1d94544bcd71f551af67bbc4c1d733ca750ea8c8306f9 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : f4be922dd9effd15e3706b4058395e451553863d1460b0a455f96b767608416a KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 24cc3298694f3c345fc95d587207742d669928934ba989fa15660e41f31cd390 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 99ec1652af0220656f093f5d6796ec578011284a53ce1927fd20abf37e8dd4c8 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 0e2f61aa54d9e9e6fc9b86269ebc3baf5a6534bab26cc028dea7133664884579 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 4cc2c31e422ce617765ba003dceeefbef64669bea5f42110476315a532f0f8fd KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : ce46b1234ac79c7b0b4901b2df0dd612b34a7205c0980a8cb4b941d3ceb2c4b2 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 9bcf8c15f111be6adb7c5c7601e47de6ec0ecfa226e471ee8d5728cc9e1fb1dd KO

TypeError: Cannot read property 'toBytes' of undefined
Deploy : 13e18a7f6798e43291c0abf0dd8e8b027fd0d8428a62ec5455682aab7a558d20 KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 97,173,237,66,103,149,177,160,67,115,215,213,18,238,8,215,48,27,162,112,22,227,121,217,178,101,136,128,27,137,254,62, 
Deploy : 23cfd1c93c83c4056a3f14846270de7fe7131a6b2639873472d33403038651fb KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 100,92,156,63,79,26,121,52,252,173,176,216,55,82,223,216,191,161,173,65,75,247,115,66,207,184,30,9,106,35,70,7, 
Error: Tried to unwrap Error: 0
Deploy : b691e73b537a9431c3416c99bd615d25a285e5e3b4cc226a82426f89ae23c112 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 049f058cf0bba42788ccac4f25633204beecde1590a0ee92371fffd2d930ec6f KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : bfd2542e3ba4bf6bcf28ef5965233c34be0cc32c25191de782ef76f5a33460d0 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 754f0ecf726d66032dfb3ee1ad181585fb109f976dbc22fa7759173193119516 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 6d7dbd3f2c72a1fc3a2effa18be9e2b7cf6a4574bdb91bbe171c56dd1285321a KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : e8e5b1c7f395a03820fa26200a26f3f10f2fa6a009508bd5688c374b4fb5fb7c KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 443fc44bafb3ab767f3398bd2abb7599e15b4e6bae92a2a1c69363f5fc5c1edc KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : e6a035f2c8335441a5a603b46c3a73bdd118bdb6e70ba7a6f2b5af7c12305be2 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 3aeb2ad2b209291fa3d15166cdd6768cfeae91414533a39961b3c69dd83bf8f7 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 4d455de4a36ce0fde47b6a84e59652e4ddd103f59e91fb694d04b308912af979 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 4017c4c3ba47d5d26934247ecdf4c41d06005f4c7d5e1723317fd5877449e8b2 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : d45d3ca68bee50dcf5b139a723d407b4b6a237c3081b1bffed15835206eb61e4 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 1eea0ed5ab843af2c5cb189bb13b3094d07d9389e2e04417e26c8c2a53004a6b KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : c7509dec5f8fbfa6a2753c2f5980691ba8eba5dc187f38dea04629d61d2473a7 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 5899add0de77771afebfde21ee47ea1963bc3b854af444bcc1d6c95840f513e4 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : e2bed34a3b8ea4af52c39f0baef6492ae05cd59da3883328e34eb8b943b15425 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 308c11f2d81712be993b7913b633798260d84d017328f43b29da8052f01a2591 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : e67f0d6a221a2228b1dff42af4aeb6082cc1506b4f751317add086be5c841c36 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : fb60fd74f35738d161a189452258388b994bfa25a436f04d23d1621e47d9962f KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 1db9100a28d6f21f55d175d3e9e6d2d8a16ec3394e6660c8ac6c5106aa4bbab6 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : cab7a742e660cb84fb36a0a7ee432c397dd9f56f1f27f38d5994fb14bb973ee1 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 2d8c8a81fc2a65eadbe47f3a79105321db496cfcc05a2babf7e35550f9d809e0 KO

TypeError: Cannot read property 'toBytes' of undefined
Deploy : cbed94db7c5a7e4a544a11d85f4c46e393f7b4fc31af586ea0251b5769a8216e KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 142,198,68,189,150,2,115,237,5,144,132,198,167,199,205,226,232,64,62,239,179,213,132,170,220,45,191,103,235,22,254,92, 
Deploy : 0b58224988d377e412e7d7e108c547efd8ea3984f85e0b1e516f26c9ead09fd6 KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 108,149,2,65,143,21,59,79,225,229,120,1,213,140,35,15,198,37,133,171,106,30,176,50,0,91,33,213,197,13,113,132, 
Error: Tried to unwrap Error: 0
Deploy : 0fc55ccbdb0c9a145e0517c08c4068b43a942e0147f6393d89a4690cb788087c KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : ee6c7b76f2d75ae364413509327c2b38aa9eb0dc85cdaab3b99902238f336a37 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : d057d876113c37160bd297e4792a002c8e0d477dc62c8b36f3cfc637f4ad596c KO

TypeError: Cannot read property 'toBytes' of undefined
Deploy : 244d731044e1b7059507b9191a041844e93c8afa8789f03b5c5632ea85a7e286 KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 97,173,237,66,103,149,177,160,67,115,215,213,18,238,8,215,48,27,162,112,22,227,121,217,178,101,136,128,27,137,254,62, 
Error: Tried to unwrap Error: 0
Deploy : 1b53b81a7df5aea7d899663787ca4ae23482997612ba5312cb2521602b5b7f66 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 2d025da629812d3c2e84d11c21ba7e6dd9ac13e94b4ba4c79a7b3c86c1b381a3 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 34f48231b501c112edfc16f6a04fe26bda2fcea129d078f8f41cabedebbb5d39 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : e5aac80274490685a015e954b8e761b3996358967b3896641b675e9f6db68703 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : d69b919b2a1056b3fa59c88863a11c989496c40e2ee1e9f4d5fe4b7f08d7fcc4 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : e685b1996e93a2d099f14bc94fb696f29a3ea7be232c5db3d035098c677ad0f6 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 3f4df2f68a94a7340a9a010b26a9a3425b685dad9cd17ab359cbe66687d2becc KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : efe6bef366b4bc9ead3b7e04be6f8eac8ed42da8a55dc4eda922f7927bd3dfb3 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: 0
Deploy : 2c36fe6ca5c7c8da052d22b5c08f5eeecd8afc00ce4aaea0f330a554b953804d KO

TypeError: Cannot read property 'toBytes' of undefined
Deploy : bd2f9540c284d315e940b9febdc7355890a599e60f2f64b125452398a9f5cf5a KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 24,113,240,250,72,247,233,181,9,212,125,35,233,170,25,107,52,252,206,232,94,83,178,41,85,212,199,98,95,67,193,96, 
Error: Tried to unwrap Error: 0
Deploy : 1c09636fc22a4c54598b370db181c16f26c0e4a735b587710820bcd6cc09a456 KO

TypeError: Cannot read property 'toBytes' of undefined
Deploy : 5380b160ad62b3cabc83a62eaec9ac1cfdddfb16753da963967486d059c42c45 KO

Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 235,140,1,60,208,51,62,107,225,224,204,71,49,191,96,130,207,40,200,191,183,201,174,30,65,25,171,56,160,128,215,160, 
Error: Tried to unwrap Error: Left over bytes
Deploy : 482a4704c4835205e70bcf70379cb5250a063e35b0d73f7cfb54263fb58cb478 KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : 0cace0cdd32e32f2ae9590ddcfcd3017d42bf08a426f29f60cddf730e74b2f8e KO

TypeError: Cannot read property 'toBytes' of undefined
Error: Tried to unwrap Error: Left over bytes
Deploy : aa83cd17bd3a2147b40737b58d35fc102f39125c1d6c756e8e58eed1e7229efd KO

TypeError: Cannot read property 'toBytes' of undefined
```

**Comment by KillianH** [comment]
```
Failed to retrieve transfer e14d29611e67dfbae4ce05579b5983047144bf77ca351a654c9831b89c56636e                                                                                                                                                                                                                               
 Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 51,123,113,32,158,89,66,222,223,238,180,56,54,77,245,218,240,248,38,191,211,142,123,240,211,227,108,57,96,140,129,233,                                                                                                                  
                   got: 81,64,119,139,86,217,155,201,39,236,254,189,30,12,12,4,71,131,167,81,23,122,124,101,81,236,188,201,215,139,16,121.                                                                                                                                                                                  
     at Object.deployFromJson (/snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:81360)                                                                                                                                                                                                                               
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58603                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                                                                                                                                  
     at ErrImpl.unwrap (/snapshot/node_modules/ts-results/result.js:53:19)                                                                                                                                                                                                                                                  
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58621                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                                                                                                                                  
 Failed to retrieve transfer d388e4e79d1e29bf7c774d79f2bb6fd8c94cb208ddb8cd6e48612107236840bd                                                                                                                                                                                                                               
 Error: Tried to unwrap Error: Error: Invalid deploy: bodyHash missmatch. Expected: 11,192,21,161,48,90,22,10,87,193,226,186,252,139,244,245,89,94,191,184,210,108,214,246,13,115,159,248,117,6,201,146,                                                                                                                    
                   got: 113,42,0,77,113,88,168,98,255,223,164,162,77,15,242,86,197,185,185,187,240,116,183,44,71,164,233,104,22,151,69,96.                                                                                                                                                                                  
     at Object.deployFromJson (/snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:81360)                                                                                                                                                                                                                               
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58603                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                                                                                                                                  
     at ErrImpl.unwrap (/snapshot/node_modules/ts-results/result.js:53:19)                                                                                                                                                                                                                                                  
     at /snapshot/node_modules/casper-js-sdk/dist/lib.node.js:1:58621                                                                                                                                                                                                                                                       
     at runMicrotasks (<anonymous>)                                                                                                                                                                                                                                                                                         
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Two transfer are affected on mainnet

**Comment by KillianH** [comment]
Hey @hoffmannjan any update on this ? :)

**Comment by George-cl** [comment]
> Hey @hoffmannjan any update on this ? :)

This is kind of on me - need to finish my review of the changes - hoping to finish tonight @hoffmannjan

**Comment by KillianH** [comment]
> > Hey @hoffmannjan any update on this ? :)
> 
> This is kind of on me - need to finish my review of the changes - hoping to finish tonight @hoffmannjan 

No problem. Does the deploy that I provided aren't included in the fix ?

File: src/lib/CLValue/Key.ts [hunk 1]
```diff
@@ -7,14 +7,15 @@ import {
...
+  CLByteArrayType,
   CLByteArrayBytesParser,
   CLURef,
   CLURefBytesParser,
   CLAccountHash,
   CLAccountHashBytesParser,
   CLErrorCodes,
   KeyVariant,
-  ACCOUNT_HASH_LENGTH,
+  // ACCOUNT_HASH_LENGTH,
```
Comment (George-cl) [inline src/lib/CLValue/Key.ts]: Can this be removed if it's not being used?

File: src/lib/CLValue/Key.test.ts [hunk 2]
```diff
@@ -101,6 +101,31 @@ describe('CLKey', () => {
...
+  //   );
+
+  //   const fromJson = CLValueParsers.fromJSON(json).unwrap();
+
+  //   console.log(fromJson);
+
+  //   // expect(json).to.be.deep.eq(expectedJson);
+  //   // expect(fromJson).to.be.deep.eq(myKey);
+  // });
+
```
Comment (George-cl) [inline src/lib/CLValue/Key.test.ts]: Can this be removed if it's not being used?
Looks like its been superseded by the test above

**Review by George-cl — CHANGES_REQUESTED** [review]
Changes look good to me, I've marked two bits of commented code that can probably be removed now. I think @KillianH wants clarification on if it fully resolves all the examples he shared.

**Comment by hoffmannjan** [comment]
> > > Hey @hoffmannjan any update on this ? :)
> > 
> > 
> > This is kind of on me - need to finish my review of the changes - hoping to finish tonight @hoffmannjan
> 
> No problem. Does the deploy that I provided aren't included in the fix ?

Hi @KillianH, I think we need to split this into few different issues, as most of the failing deploys shows problem with different `CLType`, also it involves some changes how `RunTimeArgs` works so this is pretty big change to do. 
I think I will have time to tackle it after new year, but will try to create issues and tag you (so you will be notified about changes) this week :).

**Review by George-cl — APPROVED** [review]
